# Generated by Django 3.1.1 on 2020-09-30 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpMan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('man_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.empman')),
            ],
        ),
    ]
