# Generated by Django 3.1.1 on 2020-09-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200930_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='man_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
